[project]
name = "nelfo-invoice"
version = "0.1.0"
description = "Nelfo Invoice class, contains validation and read/write"
readme = "README.md"
authors = [
    { name = "Anders", email = "as@solarnorge.no" }
]
requires-python = ">=3.14"
dependencies = [
    "pycountry>=26.2.16",
    "pydantic>=2.12.5",
]
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/nelfo_invoice"]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-cov>=7.1.0",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
